app-properties:
  test-username : testUsername
  test-password : Didrltjr3!@
  test-email : test@gmail.com
  test-nickname : testNickname
  regexEmail : ^[A-Za-z0-9_\.\-]+@[A-Za-z0-9\-]+\.[A-Za-z0-9\-]+
  regexPassword : ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{8,}

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true